### ISSUE TITLE
guru1d1f example crashes

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#103]
When we run this in the gi_v2 branch, we get the output
```
creating data then run guru interface, default opts...
spreadcheck NU pt not in valid range (central three periods): kx=-0.00278275, N1=200000 (pirange=1)
```
even though the frequencies are located in the interval [–π, π]. As a result, subsequent calls cause segfaults.

**Comment by ahbarnett** [comment]
Fascinating. examples/guru1d1f works fine for me - no such error. Your error report is because I just changed the default o.chkbnds from 0 to 1.  (I think it's more sensible a default since otherwise the user can cause segfaults which crash out of matlab, etc.)

C++ folks tell me such a macro is bad, since it should be an inline function and the compiler will make it just as fast. I never tried that out, since why break something that works?

Now I have to understand your PR fixing this...

**Comment by ahbarnett** [comment]
I'll close, even though your compiler behaved differently from mine, and I can't test yours.
