### ISSUE TITLE
Plan interface function names

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#108]
I was looking over these to make sure we have the same names in cuFinufft and saw that we have the following function names: `finufft_default_opts`, `finufft_makeplan`, and `finufft_setpts`. For consistency, shouldn't it be `finufft_make_plan` and `finufft_set_pts`? (I don't think we want to change `finufft_default_opts` to `finufft_defaultopts` – too many breaking changes already.)

**Comment by ahbarnett** [comment]
hmm - I say not worth changing. It's perfectly clear as is. We don't use strict camel case or underscores anywhere - are you going to change all the nufft_opts and spread_o... too? ;)

**Comment by janden** [comment]
We seem to be using underscores pretty consistently elsewhere other than for `makeplan` and `setpts`. Why would we change the opts structs?

**Comment by ahbarnett** [comment]
There are many ``nufft_opts`` fields that break either convention - they were done by feel, with various abbrevs to make things not too long. Maybe because of familiarity I vote not to change the func names either. they are all of form finufft{f}_foobar except default_opts and that has a very different flavor so it's ok.

**Comment by janden** [comment]
Ah I see. Ok let's leave it then.
