### ISSUE TITLE
change py module name to finufft not finufft_cpp

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#123]
for clarity / simplicity.

**Comment by ahbarnett** [comment]
relatedly, are we keeping finufftpy as the py pkg name? (not finufft?)

**Comment by janden** [comment]
> relatedly, are we keeping finufftpy as the py pkg name? (not finufft?)

I think changing it would be better, maybe that would cause problems for downstream users? On the other hand, we're already breaking quite a few things, so maybe it doesn't matter too much.

**Comment by janden** [comment]
By the way, for cuFinufft, the pip pacakge name is `cufinufft`, so that would mean `finufft` is a better choice here.

**Comment by ahbarnett** [comment]
I don't know how many python users there are (does pypi tell us?).  However, I agree w/ the change.

The submodule name finufft_cpp is an indep issue and I leave you guys to decide if it should change.

**Comment by janden** [comment]
> I don't know how many python users there are (does pypi tell us?). However, I agree w/ the change.

There's no way to tell exactly how many users there are, but we can look at [number of downloads](https://pepy.tech/project/finufftpy). In total, there's been more than 15000 downloads, averaging about 272 a week. I strongly suspect that many of these are due to ASPIRE, however. Each time we run our CI, it does `pip install finufftpy` a couple of times.

> The submodule name finufft_cpp is an indep issue and I leave you guys to decide if it should change.

Yeah that has more to do with the ctypes conversion, which is in the works, but not for this release, I think.

**Comment by ahbarnett** [comment]
We have taken over the world! ;)

**Comment by lu1and10** [comment]
Fixed in commit f3d2352c1040316b4eaec5ebefbe6def7ad41f50
