### ISSUE TITLE
Building FFTW from source in Docker container

### ISSUE THREAD

**Issue by janden** [flatironinstitute/finufft#155]
What's the reason for doing this? It currently takes up a lot of time. Is there some reason we can't just do `yum install fftw-devel` here?

**Comment by ahbarnett** [comment]
@lu1and10 explained the reason since I asked the same thing. Here's our exchange (me then him):
Maybe there is a solution now?

_This is very exciting!
I like the way you copy the relevant make.inc.* to make.inc.
This means we can guarantee the make.inc.* are supported and work on the stated machine.
(Maybe they should get a more specific name now that matches the Travis machines).

Questions:
1) why is it running for many minutes? (eg 14 min on mac). What is taking so long? The tests take a few secs usually (maybe 20 s including compile).

2) why is xenial needing to install fftw3 from source? (that's a huge pain and I assume v slow). But the mac osx already has it in xcode?  Surely xenial has libfftw3 and libfftw3-dev or whatever pkgs we need?

3) The main next step is to make numerical checks, since apart from basicpassfail{f} they are not being done yet. For C++ testers with stdout I relied on numdiff, but that's not very available. Either we could ship it, or, simpler, make more extensive pass-fails in C++ that pay attention to numerical tolerance. This is easy to do for the py wrapper tests you have going, in a py script. (The old accuracy_speed_tests.py can be updated to test whatever features of your new interface...)

4) minor point: can stderr vs stdout be separated? They seem to be mixed together in the log-files. In my check_finufft.sh script I separate them._

Dear Alex,
For the questions you have for ci,
1). Most time is spent on brew updates and brew install things(fftw,libomp) for mac, and configure/compile fftw for linux, the actual compile and test is fast.

2). For mac it does not have fftw, we use brew to install in the ci script. For xenial, we are not actually using xenial, we are using a docker image "manylinux2010_x86_64" on the xenial OS, this "manylinux2010_x86_64" is a popular linux image so that the dynamic libraries or python wheels compiler in this docker image container is compatible in most linux systems(that's why the name is called manylinux2010_x86_64).

3). For the current ci script, I just run `make test` and `make python` or `make docker-wheel`. The ci will return false if any of the tests return non zero.
All the tests in `make test` pass, but you are right, it's not checking numerics with numdiff, I can install numdiff in the ci script.

4). The log file in the travis website prints everything to stdout, not sure how to set the travis ci script to separate, I will check.

**Comment by janden** [comment]
So there's two ways around this:

- For the manylinux image, it's based on CentOS (if I've understood correctly), so we can run `yum install fftw-devel` and it'll install it from RPM. (This is what @garrettwrong did for the cuFinufft Docker [here](https://github.com/flatironinstitute/cufinufft/blob/master/ci/docker/cuda10.1/Dockerfile-x86_64).) This should be much faster than compiling from source.
- If we do need to compile from source (as seems to be the case for macOS), we can speed things up by using the fact that Docker can cache containers at intermediate stages. This way, only commands that change between subsequent runs need to be re-executed. I haven't played around with this yet to say how it'll work exactly, but we are able to do this in the Kymatio CI, for example (see [here](https://jenkins.flatironinstitute.org/job/kymatio/job/dev/69/console), note the `Using cache` lines). The key is to run the different install commands in a Dockerfile instead of the `build-wheels.sh` script for the cache mechanism to work correctly.

**Comment by lu1and10** [comment]
> * Dockerfile

I see, currently we do not a Dockerfile, `make docker-wheel` just loads the 'quay.io/pypa/manylinux2010_x86_64' image.
I will add a Dockerfile as cuFinufft does.

**Comment by janden** [comment]
Cool. I don't know if there's something special you need to do for it to cache intermediate steps (I have a feeling this is the default setting, but I may be wrong). Let us know how it goes.

**Comment by ahbarnett** [comment]
closing since continued in #163

**Comment by janden** [comment]
> closing since continued in #163

Thanks. Forgot that there was already an issue for this…
