### ISSUE TITLE
python wheel CI did not catch broken Py *kwargs typo in _destroy

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#224]
I only found a bug in the Py doc fix PR #220 by locally running make all (ie make python), rather than by the python wheels CI.
This seems wrong, and I need help to fix CI so Py interfaces are tested.

Here is the seemingly ok CI, which runs accuracy_speed_tests.py (which *does* call nufft1d1):
https://github.com/flatironinstitute/finufft/actions/runs/2476021458

However I only get the crash when I locally do the following:

```
python3 python/examples/simple1d1.py
finufft1d1 done in 0.064 s.
Error relative to max: 6.51e-11
python3 python/examples/simpleopts1d1.py
Exception ignored in: <function Plan.__del__ at 0x7f3d0b7fdcb0>
Traceback (most recent call last):
  File "/home/alex/numerics/finufft/python/finufft/_interfaces.py", line 308, in __del__
    destroy(self)
  File "/home/alex/numerics/finufft/python/finufft/_interfaces.py", line 545, in destroy
    ier = plan._destroy(plan.inner_plan)
AttributeError: 'Plan' object has no attribute '_destroy'
Traceback (most recent call last):
  File "python/examples/simpleopts1d1.py", line 21, in <module>
    F = finufft.nufft1d1(x, c, N, eps=acc, isign=iflag, debug=1, spread_debug=1)
  File "/home/alex/numerics/finufft/python/finufft/_interfaces.py", line 834, in nufft1d1
    return invoke_guru(1,1,x,None,None,c,None,None,None,out,isign,eps,n_modes,**kwargs)
  File "/home/alex/numerics/finufft/python/finufft/_interfaces.py", line 590, in invoke_guru
    plan = Plan(tp,n_modes,n_trans,eps,isign,pdtype,*kwargs)
TypeError: __init__() takes from 3 to 7 positional arguments but 9 were given
make: *** [makefile:387: python] Error 1
```

Anyway I added the extra * and pushed to master; hope that's ok for now!

But this is a CI issue - could simple1d1 etc be added to the python CI?

**Comment by lu1and10** [comment]
passing `*kwargs` instead of `*kwargs` makes the keywords arguments to positional  arguments.

In simple1d1,  [https://github.com/flatironinstitute/finufft/blob/192616617a4ff725099595f266451ea288274e5e/python/examples/simple1d1.py#L24](https://github.com/flatironinstitute/finufft/blob/192616617a4ff725099595f266451ea288274e5e/python/examples/simple1d1.py#L24) calls the simple interface with one keyword argument `eps = 1e-9`, that's why it breaks.

While in accuracy_speed_tests.py which CI calls, all simple interfaces are called with positional arguments no keywords arguments(non set options are set to default). That's why the CI passes. Surely we can include simple1d1.py and test the feature of keyword arguments for function calls.
