### ISSUE TITLE
Surprisingly large errors with single-precision NUFFTs

### ISSUE THREAD

**Issue by mreineck** [flatironinstitute/finufft#231]
The snippet below is a shortened version of `accuracy_speed_tests.py`, adjusted for single-precision transforms. When run for type 1 1D NUFFTs, the reported error seems to scale with the grid size and quickly becomes much larger than the requested `epsilon`.

I suspect that this could be fixed by doing all coordinate-related computations inside FINUFFT in double precision. The impact on performance should not be big, since the number of these calculations is much smaller than the one for kernel evaluation, spreading or interpolating.

If this is expected behaviour, please feel free to close this issue!

```python
# Jeremy Magland, Sept 2017.
# Alex Barnett fixed integer division issue in python v2 vs v3
#              (affected 1/2, 1/3), 10/13/17.
# Removed ms etc from ?d2 interfaces, 10/31/17. Less reruns 2/14/18.
# 2d1many and 2d2many added, painfully, Barnett 7/29/18

import numpy as np
import finufft
import math
import time

def compute_error(Xest,Xtrue):
	numer=np.sqrt(np.sum(np.abs((Xest-Xtrue))**2));
	denom=np.sqrt(np.sum(np.abs(Xtrue)**2));    # rel l2 norm
	if (denom!=0):
		return numer/denom
	else:
		return 0

def print_report(label,elapsed,Xest,Xtrue,npts):
	print(label+':')
	print('    Est rel l2 err  %.3g' % (compute_error(Xest,Xtrue)))
	print('    CPU time (sec)  %.3g' % (elapsed))
	print('    tot NU pts/sec  %.3g' % (npts/elapsed))
	print('')

def accuracy_speed_tests(num_nonuniform_points,num_uniform_points,eps):
	nj,nk = int(num_nonuniform_points),int(num_nonuniform_points)
	iflag=1
	num_samples=int(np.minimum(5,num_uniform_points*0.5+1)) # number of outputs used for estimating accuracy; is small for speed

	print('Accuracy and speed tests for %d nonuniform points and eps=%g (error estimates use %d samples per run)' % (num_nonuniform_points,eps,num_samples))

	# for doing the error estimates
	Xest=np.zeros(num_samples,dtype=np.complex128)
	Xtrue=np.zeros(num_samples,dtype=np.complex128)

	###### 1-d cases ........................................................
	ms=int(num_uniform_points)

	xj=np.random.rand(nj)*2*math.pi-math.pi
	cj=np.random.rand(nj)+1j*np.random.rand(nj);
	fk=np.zeros([ms],dtype=np.complex64)
	timer=time.time()
	ret=finufft.nufft1d1(xj.astype(np.float32),cj.astype(np.complex64),ms,fk,eps,iflag)
	elapsed=time.time()-timer

	k=np.arange(-np.floor(ms/2),np.floor((ms-1)/2+1))
	for ii in np.arange(0,num_samples):
		Xest[ii]=np.sum(cj * np.exp(1j*k[ii]*xj))
		Xtrue[ii]=fk[ii]
	print_report('finufft1d1',elapsed,Xest,Xtrue,nj)


accuracy_speed_tests(1,10,1e-6)
accuracy_speed_tests(1,100,1e-6)
accuracy_speed_tests(1,1000,1e-6)
accuracy_speed_tests(1,10000,1e-6)
accuracy_speed_tests(1,100000,1e-6)
```

**Comment by mreineck** [comment]
Just for completeness, here is m local output from this script:

```
Accuracy and speed tests for 1 nonuniform points and eps=1e-06 (error estimates use 5 samples per run)
finufft1d1:
    Est rel l2 err  1.37e-06
    CPU time (sec)  0.0096
    tot NU pts/sec  104

Accuracy and speed tests for 1 nonuniform points and eps=1e-06 (error estimates use 5 samples per run)
finufft1d1:
    Est rel l2 err  1.3e-05
    CPU time (sec)  0.00607
    tot NU pts/sec  165

Accuracy and speed tests for 1 nonuniform points and eps=1e-06 (error estimates use 5 samples per run)
finufft1d1:
    Est rel l2 err  0.000158
    CPU time (sec)  0.00816
    tot NU pts/sec  123

Accuracy and speed tests for 1 nonuniform points and eps=1e-06 (error estimates use 5 samples per run)
finufft1d1:
    Est rel l2 err  0.00236
    CPU time (sec)  0.00658
    tot NU pts/sec  152

Accuracy and speed tests for 1 nonuniform points and eps=1e-06 (error estimates use 5 samples per run)
finufft1d1:
    Est rel l2 err  0.0156
    CPU time (sec)  0.00854
    tot NU pts/sec  117
```

**Comment by ahbarnett** [comment]
Hi Martin,
Thanks for this, and for your email today. Yes, the rounding error loss is expected to be around eps_mach times the largest Fourier mode dimension - I reported this in the original FINUFFT paper, Remark 9:
https://arxiv.org/abs/1808.06736
This does impact large 1d transforms in single-prec.
In general, I'm not sure there's a way around this, because unlike the FFT (which is unitary), the condition number of the NFFT problem can be arbitrarily large.

I'm not sure how "coord-related" calcs could be done in doubleprec without requiring the x_j NU input pts also in double. In which case it woudl just be the (smaller) c_j array that would be single. To me a mixed-precision code is not worth the complication.

I will say that @wendazhou enda has gotten some very impressive avx512 single-prec w=8 spreading and sorting going, that will make single-prec more desirable once we bring it in.

We will also be interested in bringing in your improved kernel to get that bit of extra accuracy.

PS your attachment was erased by one of our institutions. Feel free either to change the suffix to a non-executable one, or point to it in your repo, etc.  Your PNG plots from last time were impressive.

I think since this isn't a bug, I'll close it as an Issue.
Best wishes,  Alex

**Comment by mreineck** [comment]
Thanks for the detailed reply!

> I'm not sure how "coord-related" calcs could be done in doubleprec without requiring the x_j NU input pts also in double. In which case it woudl just be the (smaller) c_j array that would be single. To me a mixed-precision code is not worth the complication.

This is probably due to different expectations. You emphasize the "smaller memory footprint" aspect of a single-precision transform, whereas my first thought was "faster execution" :-)
You are right that if the `x_j` are only known to within single precision accuracy, there is no way to avoid this problem.
(In radio astronomy, `x_j` are typically given in double precision and `c_j` in single precision, but symmetries allow for very compact `x_j` storage, so memory consumption is not a concern for us.) 

> PS your attachment was erased by one of our institutions. Feel free either to change the suffix to a non-executable one, or point to it in your repo, etc. Your PNG plots from last time were impressive.

Sorry, I had forgotten that your mail server dos not like Python attachiments. I'll resend and add a few performance plots!
