### ISSUE TITLE
(minor) remove python vs python 3 distinction in makefile and docs

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#64]
All is python 3 now. So, all should use the command python and assume the user has the version they want installed.

**Comment by janden** [comment]
I would still keep `python3` in the Makefile and elsewhere. In most systems, `python` still defaults to Python2.

**Comment by janden** [comment]
For what it's worth, on Ubuntu 20.04, `python` doesn't exist (you have to install the `python-is-python3` package for it to redirect to `python3`). I think the same is true on Debian 10.

**Comment by ahbarnett** [comment]
that's kind of crazy, since having a python executable is in my mind like having bash.

One idea is have the makefile set PYTHON to python if it exists, python3 otherwise, and use that.
But I want to get rid of duplication in makefile (line 254-261).
Sounds good?

**Comment by janden** [comment]
I think the issue is more that a lot of legacy Python 2 scripts silently assume `python` refers to `python2`, which will cause a lot of problems if you switch that to mean `python3` (some scripts may execute fine but have unintended behavior). This way, those scripts will crash and force the author to explicitly specify `python2` or `python3`. More info in [PEP 394](https://www.python.org/dev/peps/pep-0394/#recommendation).

What was the underlying issue? Why can't we just specify `python3`?

**Comment by ahbarnett** [comment]
Maybe Joakim & Libin can help decide what's best here. Issues as I see them are:
1) we'd like "make python" (whatever it does) to work out of the box on as many default systems as possible.
2) power pythonistas will go into their own py environment anyway, in which "python" is 3 or whatever they want. Eg "pip3" will fail in their environment (at least it does for me).
3) makefile smells wrong having duplicate python and python3 tasks.
4) python wrappers and scripts work in v2 and v3.
In Libin & my new branches (guruInterface_v2 and alexguru) we simply use python/pip and assume item 2) above.
[Caveat: I get very confused w/ python config, eg mine is currently broken.]
Thoughts?

**Comment by janden** [comment]
> we'd like "make python" (whatever it does) to work out of the box on as many default systems as possible.

Agreed. If people have non-standard configs, that's for them to worry about.

> power pythonistas will go into their own py environment anyway, in which "python" is 3 or whatever they want.

According to PEP 394, a virtual environment (such as venv, virtualenv, or conda) should provide *both* `python` and `python3` (the former being a symlink to the latter). So `python3` should work in this case.

> Eg "pip3" will fail in their environment (at least it does for me).

There may be some issue with your install. Something `pip` (and other high-level Python tools) are not properly installed in the path. What you can do then is run it through the Python interpreter (which should be in the path) using `python3 -m pip` (see [the pip User Guide](https://pip.pypa.io/en/stable/user_guide/#id11)). This is considered the *safest* way of running these commands, since you're making sure that you're running the same `pip` as the one that `python3` sees.

> makefile smells wrong having duplicate python and python3 tasks.

Agreed. There's maybe a clever way to refactor these to remove duplication.

> python wrappers and scripts work in v2 and v3.

Sure, but as the top comment says, Python 2 is out. Do we have any reason to support it? Have any users indicated that they'd like to run it in Python 2? It's end-of-line. The latest Linux distributions don't even have it installed by default. In 2019, it had an estimated share of 10% (see [Python Developers Survey](https://www.jetbrains.com/lp/python-developers-survey-2019/#PythonVersions), which has a lot of other interesting data). Not having Python 2 as a dependency will also simplify CI testing later on.

I don't think it's a good idea to have the install break for systems that do not have the `python` in the PATH (which will increasingly be the case). If we really want to keep supporting both Python 2 and Python 3, there's probably a clever way to auto-detect which is available and run that (in order of preference: `python`, `python3`, `python2`?). But is it worth the hassle?

**Comment by ahbarnett** [comment]
All good. So what do you recommend "make python" does in the makefile?
Here's a proposal, a tweak on Libin's. Please see if make sense (I didn't run it yet):

# python interfaces (v3 assumed)...
# use whichever avail of python/python3, see
# https://stackoverflow.com/questions/28480240/makefile-use-exe1-if-exists-else-exe2
ifeq ($(shell which python3),)
  PYTHON = python
else
  PYTHON = python3
endif
python: $(STATICLIB)
ifeq ($(PREC),SINGLE)
	@echo "python interface only supports double precision; doing nothing"
else
	(export FINUFFT_DIR=$(shell pwd); cd python; $(PYTHON) -m pip install .)
	$(PYTHON) python/test/python_guru1d1.py	
	$(PYTHON) python/test/demo1d1.py
	$(PYTHON) python/test/run_accuracy_tests.py
# add any other py unit tests here.
endif

**Comment by lu1and10** [comment]
I think testing whether python3 is installed or not is a good idea. I'm not
sure this is a standard way for python package installation.
Joakim, do you think this is good enough?

**Comment by janden** [comment]
> All good. So what do you recommend "make python" does in the makefile?

Honestly, I think setting `PYTHON=python3` should be enough and letting users specify another binary in `make.inc` should do it. I'm not convinced that the situation of `python` existing (and points to the Python 3 interpreter) with `python3` not existing is all that common. (System Python installations provide `python3`, virtual environments provide `python3`, and so on.) So why don't we just keep things simple and assume `python3` exists? If the user has some non-standard (or broken) Python installation, it'll fail and they will change the relevant variable in `make.inc`. Perhaps I'm missing something here?

**Comment by ahbarnett** [comment]
We decided that `python` is whatever the user wants to use. It should be `python3` if they set up conda etc right. (I also checked that so far it's still working in my laptop's python 2.7 too, as of 277b69a).

**Comment by janden** [comment]
Again, this is not the default on many systems. It would be better to make the default `python3`, alternatively with a PYTHON variable in the Makefile. To make things more portable, we should also be calling `pip` as a module, like `python3 -m pip` (or `$(PYTHON) -m pip`, which ensures that we're using the same `pip` as the Python executable.

**Comment by ahbarnett** [comment]
Hi @lu1and10  can you keep Joakim's last comment in this (closed) issue in mind for the makefile - thanks, Alex

**Comment by lu1and10** [comment]
Sure, I will make a note.
