### ISSUE TITLE
FFT with ntrasform=2 with guru interface is slower than two separate FFT calls with old interface

### ISSUE THREAD

**Issue by RaulPPelaez** [flatironinstitute/finufft#69]
Let us run two batched FFT dominated type 1 transforms and compare the guru interface with the old interface. 
One would expect the fft part of the algorithm to take at most twice the time as the combined fft time of two old interface calls. However, I am consistently seeing worse performance, which hinders the final speedup in this case.

I can see this by running the finufftGuru_test code with this:

```bash
$ ./finufftGuru_test 2 1 3 128 128 128 10000 1e-4 1 1 2.0
------------------------GURU INTERFACE---------------------------
[finufft_plan] 3d1: (ms,mt,mu)=(128,128,128) (nf1,nf2,nf3)=(256,256,256) batch=2
[finufft_plan] kernel fser (ns=5):		 0.000455 s
[finufft_plan] fftw plan (mode 64):		 0.0102 s
plan creation for 2097152 modes: 0.0108 s
[finufft_setpts] sort (did_sort=1):	 0.000884 s
setpts for 10000 src points: 0.00089 s
[finufft_exec] spread:			 0.143 s
[finufft_exec] fft :			 1.48 s
[finufft_exec] deconvolve :		 0.021 s
exec 2 of 10000 NU pts to 2097152 modes: 1.64 s 	1.22e+04 NU pts/s
finufft_destroy completed in 0.0213 s
------------------------SIMPLE INTERFACE-------------------------
[finufft_plan] 3d1: (ms,mt,mu)=(128,128,128) (nf1,nf2,nf3)=(256,256,256) batch=1
[finufft_plan] kernel fser (ns=5):		 0.00142 s
[finufft_plan] fftw plan (mode 64):		 0.0034 s
[finufft_setpts] sort (did_sort=1):	 0.000932 s
[finufft_exec] spread:			 0.113 s
[finufft_exec] fft :			 0.448 s
[finufft_exec] deconvolve :		 0.0113 s
[finufft_plan] 3d1: (ms,mt,mu)=(128,128,128) (nf1,nf2,nf3)=(256,256,256) batch=1
[finufft_plan] kernel fser (ns=5):		 0.000317 s
[finufft_plan] fftw plan (mode 64):		 0.00121 s
[finufft_setpts] sort (did_sort=1):	 0.000628 s
[finufft_exec] spread:			 0.111 s
[finufft_exec] fft :			 0.434 s
[finufft_exec] deconvolve :		 0.0113 s
2 of	10000 NU pts to 2097152 modes in 1.16 s      	1.72e+04 NU pts/s
	speedup: T_finufft3d1_simple / T_finufft3d1 = 0.693
```
It gets better with ntransforms > 3, but still I do not understand why it would be slower in any case.  
Type 2 or 3 transforms yield similar behavior.
I am only seeing this behavior with a number of cores greater than 2. 
It might be due to some bad decision FFTW makes in this particular situation or maybe just a quirk of the systems I tried. But it might have an easy solution by tweaking the FFTW wisdom somehow.

**Comment by ahbarnett** [comment]
Dear Raul,
Hmm, yes, this is entirely a comparison of FFTW called with "fftw_plan_many_dft" vs the simple interface, and you are right, it sometimes happens to be slower, presumably because of >1 threads trying to access RAM at the same time.

Several thoughts:

0) You can directly pass in FFTW plan modes to guru test currently by eg inserting a line at l.228 of finufftGuru_test.cpp and re-making test/finufftGuru_test from the top dir:
  opts.fftw = FFTW_MEASURE;
This speeds up fft by 2x on my i7, and equalizes the two calls better too.
You can then try any codes from fftw3 docs.

1) Keep in mind the guru interface is designed to give a speedup with *many small* problems, to reduce the fft plan lookup overhead, and spread sort overhead, not bigger ones like you're doing. Big ones are only likely to suffer due to more RAM being accessed at the same time. Although, the reason we're creating the guru interface is to allow this kind of experimentation.

2) The same appears true in matlab's version of fftw:
>> a=rand(256,256,256,2)+1i; tic; fftn(a); toc      % this is a hack to do two 3D fft's at once
Elapsed time is 0.270064 seconds.
>> a=rand(256,256,256)+1i; tic; fftn(a); fftn(a); toc     % sequential is faster
Elapsed time is 0.214715 seconds.

3) Also, keep in mind you're incorrectly calling the tester (it had no effect, I checked), since you're missing a field. You want, eg:   (debug=1, sprscheme=1, sort=2)
./finufftGuru_test 2 1 3 128 128 128 10000 1e-4 1 1 2 2.0

4) If you're really fft-dominated (but you're probably not; I'm guessing your Issue is just a test case), upsampfac=1.25 makes it much faster in 3D!

5) I will be rewriting the core of guru in coming days, so will get back to you.

Please post what you find re the above,      Alex

**Comment by ahbarnett** [comment]
I just pushed my thought 0) to the branch. Thanks, Alex

**Comment by RaulPPelaez** [comment]
Thanks for the insights, Alex.
0) Cool!, seems like a better default. Although one never knows with FFTW.
AFAIK FFTW_MEASURE does exactly that and measures the performance to make decisions for next runs (which according to the docs might take seconds). Personally this is what I would prefer, although it hurts the one transformation use case by increasing initialization time one can just tweak the option if necessary. 
1) I understand I drifted away from the original intend of the guru interface. Our use case usually involves spreading a three component field to a 3D grid. And there might be a lot of particles, thus my test. 
In any case a small number of big transforms should also benefit from the guru interface. Traversing the marker positions and evaluating the kernel only once instead of ntransform times must be beneficial to some degree, right? (and it is indeed in my machine)
3) Oops, I must have missed it, a lot of numbers... I was focusing on fft and spread so I guess I was lucky.
4) It is just a test case indeed, but not that far from real world. Being the spreading so fast I can see our runs being fft dominated often. Which I think is a good thing, if fftw is the bottleneck you are probably doing the best that can be done. I will keep in mind the upsampling factor!

Thanks for your comprehensive answer Alex,
Raul.

**Comment by ahbarnett** [comment]
v2 has appeared and you are able to control the FFTW plan mode directly via opts.
