### ISSUE TITLE
sparse NUFFT

### ISSUE THREAD

**Issue by Sketos** [flatironinstitute/finufft#74]
This is not an issue, but rather a question about finufft.

It is not specifically mentioned in the documentation, but I was wondering if finufft is equipped to take advantage of sparse matrices when computing the nufft2d2(). If not, is this something that can be easily implemented?

**Comment by ahbarnett** [comment]
Dear Stekos, I don't understand the question, since there are no matrices under the hood in the algorithm. Spreading is done locally, then the FFT is what it is. The overall task can be phrased as a (dense) mat-vec, but you can't get around it being dense. If you had sparse vectors coming in, you would only send the nonzero elements to the NUFFT. If you only wanted a sparse set of modes out, we don't have a way to exploit that (and the FFT is usually so fast that it's not worth using sparse variants). Let me know if that doesn't answer it, Alex
