### ISSUE TITLE
guruInterface_v2 multithread segfault on icpc

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/finufft#87]
xeon
icpc (ICC) 19.0.0.117 20180804
CFLAGS = -fPIC -O3 -xHost -g -Wall
make test/finufft1d_test -j 12
test/finufft1d_test 1e6 1e6 1e-6
gets wrong math and crashes.
gdb says crash is l.314 of spreadinterp.cpp
ie, accessing kx[kk]

OMP_NUM_THREADS=1 test/finufft1d_test 1e6 1e6 1e-6
works fine, which also uses subprobs.

Also: GCC 7.4.0 works fine for all the above.

Also, reverting to master works in icpc so it's something to do with subproblem indexing change.

**Comment by ahbarnett** [comment]
narrowed down to bin_sort_multithread not doing its job. It must some weird aspect of omp nesting, that the parallel block.
To reproduce most simply:

module load intel/compiler
make clean
make test/spreadtestnd
test/spreadtestnd 1 1e6 1e6 1e-6 1 0 2

nth_u = 1 and all subgrids have same start, all wrong. then crashes.

**Comment by ahbarnett** [comment]
Solved.
Was simultaneous linking of libgomp and libiomp5  !!!
This is because -lgomp was still in the makefile. Will fix up the make.inc.linux_ICC

**Comment by lu1and10** [comment]
Thanks, was testing and had the same issue.
BTW, have some warning for the omp nest function for intel compiler 2020

"omp_set_nested routine deprecated, please use omp_set_max_active_levels
instead."

**Comment by ahbarnett** [comment]
Hi Libin -
ok, great, well, now I know, but it's terrible that there is no compiler/linker warning that two incompatible omp libs are present. It just leads to unpredictable behaviour (only in the gi_v2, not master, due to my little routine to get nthr_used, I think...) - plus a lot of stress this afternoon!

Re nesting: I use this once. Maybe you can help fix it?  I found absoluting nothing useful online about how to use the new directive, or what a level is.
Is OMP_SET_NESTED(0) equiv to omp_set_max_active_levels(1) ??  or zero?

For OMP_SET_NESTED(1) we want omp_set_max_active_levels(2), since I only use two levels at most.
What I don't get is if one does an outer parallel block with num_threads(1),
then an inner one, if nested==0, does the inner one spawn max_threads threads?
Ie, does a parallel block with only 1 thread "count" towards a nesting level?

**Comment by lu1and10** [comment]
I actually saw some compiler has a warning message when two version omp
libs is linked, but can't remember which compiler which version.
Seems the double omp lib linking was raised in
https://github.com/flatironinstitute/finufft/issues/68#issuecomment-609501650
for python too.

Tested with omp_set_max_active_levels,
omp_set_max_active_levels(0) means no parallel threading, just one thread
doing serial computation.
omp_set_max_active_levels(1) means one level threading.
omp_set_max_active_levels(2) means two level threading.

so when we use nested for 2 levels, we should use
omp_set_max_active_levels(2), otherwise omp_set_max_active_levels(1) for no
nested multithreading.
I will incorporate  in issue #88.

**Comment by ahbarnett** [comment]
cool - thanks!
meanwhile gnu makefile CXXFLAGS has repetitions that I don't understand...

**Comment by ahbarnett** [comment]
closed by commit ca546ae4174b7e2d5350113f369412a6bc7c6ca6
